1: Additional changes and updates from Platform.sh template

diff --git a/.platform.app.yaml b/.platform.app.yaml
--- a/.platform.app.yaml
+++ b/.platform.app.yaml
@@ -1,28 +1,42 @@
-# Complete list of all available properties: https://docs.platform.sh/create-apps/app-reference.html
+# This file describes an application. You can have multiple applications
+# in the same project.
+#
+# See https://docs.platform.sh/configuration/app.html
 
-# A unique name for the app. Must be lowercase alphanumeric characters. Changing the name destroys data associated
-# with the app.
-name: 'drupal'
+# The name of this app. Must be unique within a project.
+# Must be lowercase alphanumeric characters. Changing the name destroys data associated with the app.
+name: 'turbo-drupal'
 
 # The runtime the application uses.
-# Complete list of available runtimes: https://docs.platform.sh/create-apps/app-reference.html#types
-type: "php:8.3"
+type: 'php:8.3'
 
-# How many resources to devote to the app. Defaults to AUTO in production environments.
-# More information: https://docs.platform.sh/create-apps/app-reference.html#sizes
-# size:
+dependencies:
+  php:
+    composer/composer: '^2.1'
+    drush/drush: '^12'
+  nodejs:
+    n: "*"
+
+runtime:
+  # Enable the redis extension so Drupal can communicate with the Redis cache.
+  extensions:
+    - redis
+    - sodium
+    - apcu
+    - blackfire
+    - imagick
 
 # The relationships of the application with services or other applications.
+#
 # The left-hand side is the name of the relationship as it will be exposed
 # to the application in the PLATFORM_RELATIONSHIPS variable. The right-hand
 # side is in the form `<service name>:<endpoint name>`.
-# More information: https://docs.platform.sh/create-apps/app-reference.html#relationships
 relationships:
   database: 'db:mysql'
   redis: 'cache:redis'
 
-# The size of the persistent disk of the application (in MB). Minimum value is 128.
-disk: 3072
+# The size of the persistent disk of the application (in MB).
+disk: 2048
 
 # The 'mounts' describe writable, persistent filesystem mounts in the application.
 mounts:
@@ -49,34 +63,58 @@ mounts:
   '/drush-backups':
     source: local
     source_path: 'drush-backups'
-
-  '/translations':
+  # Drupal Console will try to save backups to this directory, so it must be
+  # writeable even though you will almost never need to use it.
+  '/.console':
     source: local
-    source_path: 'translations'
+    source_path: 'console'
 
 # Configuration of the build of this application.
 build:
   flavor: composer
 
-# The web key configures the web server running in front of your app.
-# More information: https://docs.platform.sh/create-apps/app-reference.html#web
+# Platformsh variables.
+variables:
+  env:
+    N_PREFIX: /app/.global
+
+# The hooks executed at various points in the lifecycle of the application.
+hooks:
+  # The build hook runs after Composer to finish preparing up your code.
+  # No services are available but the disk is writeable.
+  build: |
+    # Exit the hook on any failure
+    set -e
+
+    if [ "$PLATFORM_ENVIRONMENT_TYPE" != production ]; then
+      curl -fsS https://platform.sh/cli/installer | php
+
+      # Install the version specified in the .nvmrc file
+      # n auto
+
+      # Reset the location hash to recognize the newly installed version
+      # hash -r
+
+      # npm install
+      # npm run production
+    fi
+
+  # The deploy hook runs after your application has been deployed and started.
+  # Code cannot be modified at this point but the database is available.
+  # The site is not accepting requests while this script runs so keep it
+  # fast.
+  deploy: |
+    set -e
+    php ./drush/platformsh_generate_drush_yml.php
+    # if drupal is installed, will call the following drush commands:
+    #   - `cache-rebuild`
+    #   - `updatedb`
+    #   - and if config files are present, `config-import`
+    cd web
+    bash $PLATFORM_APP_DIR/drush/platformsh_deploy_drupal.sh
+
+# The configuration of app when it is exposed to the web.
 web:
-  # Commands are run once after deployment to start the application process.
-  # More information: https://docs.platform.sh/create-apps/app-reference.html#web-commands
-  # commands:
-  # The command to launch your app. If it terminates, it’s restarted immediately.
-  #   You can use the $PORT or the $SOCKET environment variable depending on the socket family of your upstream
-  #   PHP applications run PHP-fpm by default
-  #   Read about alternative commands here: https://docs.platform.sh/languages/php.html#alternate-start-commands
-  #   start: echo 'Put your start command here'
-  # You can listen to a UNIX socket (unix) or a TCP port (tcp, default).
-  # For PHP, the defaults are configured for PHP-FPM and shouldn't need adjustment.
-  # Whether your app should speak to the webserver via TCP or Unix socket. Defaults to tcp
-  # More information: https://docs.platform.sh/create-apps/app-reference.html#where-to-listen
-  # upstream:
-  #  socket_family: unix
-  # Each key in locations is a path on your site with a leading /.
-  # More information: https://docs.platform.sh/create-apps/app-reference.html#locations
   locations:
     # All requests not otherwise specified follow these rules.
     '/':
@@ -102,7 +140,7 @@ web:
       # Rules for specific URI patterns.
       rules:
         # Allow access to common static files.
-        '\.(avif|webp|jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
+        '\.(jpe?g|png|gif|svgz?|css|js|map|ico|bmp|eot|woff2?|otf|ttf)$':
           allow: true
         '^/robots\.txt$':
           allow: true
@@ -131,66 +169,7 @@ web:
         '^/sites/default/files/(css|js)':
           expires: 2w
 
-# Alternate copies of the application to run as background processes.
-# More information: https://docs.platform.sh/create-apps/app-reference.html#workers
-# workers:
-
-# The timezone for crons to run. Format: a TZ database name. Defaults to UTC, which is the timezone used for all logs
-# no matter the value here. More information: https://docs.platform.sh/create-apps/timezone.html
-# timezone: <time-zone>
-
-# Access control for roles accessing app environments.
-# More information: https://docs.platform.sh/create-apps/app-reference.html#access
-# access:
-
-# Variables to control the environment. More information: https://docs.platform.sh/create-apps/app-reference.html#variables
-#variables:
-
-# Outbound firewall rules for the application. More information: https://docs.platform.sh/create-apps/app-reference.html#firewall
-# firewall:
-
-# Specifies a default set of build tasks to run. Flavors are language-specific.
-# More information: https://docs.platform.sh/create-apps/app-reference.html#build
-
-# Installs global dependencies as part of the build process. They’re independent of your app’s dependencies and
-# are available in the PATH during the build process and in the runtime environment. They’re installed before
-# the build hook runs using a package manager for the language.
-# More information: https://docs.platform.sh/create-apps/app-reference.html#dependencies
-# dependencies:
-
-# Hooks allow you to customize your code/environment as the project moves through the build and deploy stages
-# More information: https://docs.platform.sh/create-apps/app-reference.html#hooks
-hooks:
-  # The build hook runs after Composer to finish preparing up your code.
-  # No services are available but the disk is writeable.
-  build: |
-    set -e
-  # The deploy hook runs after your application has been deployed and started.
-  # Code cannot be modified at this point but the database is available.
-  # The site is not accepting requests while this script runs so keep it
-  # fast.
-  deploy: |
-    set -e
-    php ./drush/platformsh_generate_drush_yml.php
-    # if drupal is installed, will call the following drush commands:
-    #   - `cache-rebuild`
-    #   - `updatedb`
-    #   - and if config files are present, `config-import`
-    cd web
-    bash $PLATFORM_APP_DIR/drush/platformsh_deploy_drupal.sh
-    drush locale:import de ../translations/fhlt.de.po
-    drush locale-update
-
-  # The post_deploy hook is run after the app container has been started and after it has started accepting requests.
-  # More information: https://docs.platform.sh/create-apps/hooks/hooks-comparison.html#deploy-hook
-  post_deploy: |
-    set -e
-      cd web
-      # Run pending deploy update hooks.
-      drush deploy:hook --yes
-
-# Scheduled tasks for the app.
-# More information: https://docs.platform.sh/create-apps/app-reference.html#crons
+# Cron jobs.
 crons:
   # Run Drupal's cron tasks every 19 minutes.
   drupal:
@@ -198,13 +177,9 @@ crons:
     commands:
       start: 'cd web ; drush core-cron'
 
-# Customizations to your PHP or Lisp runtime. More information: https://docs.platform.sh/create-apps/app-reference.html#runtime
-runtime:
-  # Enable the redis extension so Drupal can communicate with the Redis cache.
-  extensions:
-    - redis
-    - sodium
-    - apcu
-
-# More information: https://docs.platform.sh/create-apps/app-reference.html#additional-hosts
-# additional_hosts:
+# Auto update source.
+source:
+  operations:
+    auto-update:
+      command: |
+        curl -fsS https://raw.githubusercontent.com/platformsh/source-operations/main/setup.sh | { bash /dev/fd/3 sop-autoupdate; } 3<&0
